### ISSUE TITLE
transaction

### ISSUE THREAD

**Issue by zhongjixiuxing** [duoyun/mongo-tools#3]
你好，我刚接触mongodb两个月，想问这，你们在实际项目上是如何解决mongodb的事务问题？最近在我的项目中遇到这个问题，在百度，谷歌上面的资料又比较少，官网上介绍使用二次提交方式每次都需要写事务逻辑，现在真的不知如何解决好。请指教下...

**Comment by duoyun** [comment]
事务与这个项目无关啊，不要在这提issue啦 
事务可参考：
http://duoyun.org/topic/5135cb98fd6181f368071927 Data update and Transaction部分
